server:
  port: 8081

topic:
  name: topic.food.order

spring:
  kafka:
    consumer:
      group-id: "default"

  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:kafka-cloud-test
    username: sa

